---
title: "SST - assessment"
author: "Michael Sumner, Jessica Melbourne-Thomas, Rowan Trebilco"
date: "2017-5-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ICE

```{r}

## preparation
library(aceecostats)
library(raster)
library(feather)
library(dplyr)
library(ggplot2)
## local path to required cache files
datapath <- "/mnt/acebulk"



library(ggplot2)
library(tidyr)
dp <- "/mnt/acebulk/seaiceseason"

##db file
library(dplyr)
db <- src_sqlite("/mnt/acebulk/habitat_assessment_output.sqlite3")


epoch <- ISOdatetime(1970, 1, 1, 0, 0, 0, tz = "GMT")
ice_density_tab <- tbl(db, "ice_days_density_tab") %>% collect(n = Inf) %>% mutate(date = date + epoch)  %>% 
filter(!Zone == "Mid-Latitude") 

# ice_sparkline_tab <- tbl(db, "ice_days_sparkline_tab") %>% collect(n = Inf) %>% 
#   mutate(date = date + epoch) 

ice_sparkline_tab_nozone <- tbl(db, "ice_days_sparkline_tab_nozone") %>% collect(n = Inf) %>% 
  mutate(date = date + epoch)



 spark_data <- ice_sparkline_tab_nozone %>% filter(date > as.POSIXct("1981-02-15"))
 density_data <-  ice_density_tab %>% filter(days > 0, days < 365)
  gspark <-  ggplot(spark_data, aes(x = date, y = days)) + geom_line() + facet_wrap(~SectorName)
  gdens <- ggplot(density_data, aes(x = days, weights = area,  group = decade, colour = decade)) + 
    geom_density() + facet_wrap(~SectorName)  

  p <- options(warn = -1)  
  print(gspark + ggtitle("Combined zones"))
  print(gdens + ggtitle("Combined zones"))
  par(p)


```