---
title: "SST - assessment"
author: "Michael Sumner, Jessica Melbourne-Thomas, Rowan Trebilco"
date: "2017-5-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SST

```{r}
decade_maker <- function(x) {
  #cut(as.integer(format(x, "%Y")), c(1980, 1992, 2004, 2016), lab = c("1980-1992", "1991-2004","2002-2016"))
  cut(as.integer(format(x, "%Y")), c(1977, 1987, 1997, 2007, 2017), 
      lab = c("1977-1987", "1987-1998","1998-2007", "2007-2017"))
}
## preparation
library(aceecostats)
library(raster)
library(feather)
library(dplyr)
library(ggplot2)
## local path to required cache files
datapath <- "/mnt/acebulk"



library(ggplot2)
library(tidyr)

##db file
library(dplyr)
db <- src_sqlite("/mnt/acebulk/habitat_assessment_output.sqlite3")
epoch <- ISOdatetime(1970, 1, 1, 0, 0, 0, tz = "GMT")
sst_density_tab <- tbl(db, "sst_density_tab") %>% collect(n = Inf)
sst_sparkline_tab <- tbl(db, "sst_sparkline_tab") %>% collect(n = Inf) %>% 
  mutate(season_year = season_year + epoch, season = aes_season(season_year))


library(tidyr)

## loop the plots

uzones <- unique(sst_density_tab$Zone)
useasons <- c("Summer", "Winter")
iseason <- izone <- 1 
for (izone in seq_along(uzones)) {
  for (iseason in seq_along(useasons)) {
    
    ## reshape the sparkline data to key/col on min/max
    spark_data <- sst_sparkline_tab %>% filter(Zone == uzones[izone], season == useasons[iseason]) %>% 
      gather(measure, sst, -season, -SectorName, -Zone, -season_year)
    
    ## subset the density data
    density_data <- sst_density_tab %>% filter(Zone == uzones[izone], season == useasons[iseason]) 
    
  ## create the three gg objects for sparkline, min-sst, max-sst
   gspark <-  ggplot(spark_data, aes(x = season_year, y = sst, group = measure, colour = measure)) + geom_line() + facet_wrap(~SectorName)
   gdens_min <- ggplot(density_data, aes(x = min, weights = area,  group = decade, colour = decade)) + 
      geom_density() + facet_wrap(~SectorName+ Zone) 
   gdens_max <- ggplot(density_data, aes(x = max, weights = area,  group = decade, colour = decade)) + 
     geom_density() + facet_wrap(~SectorName+ Zone) 
   
   op <- options(warn = -1)
  if (nrow(spark_data) > 1)  print(gspark)
    if (nrow(density_data) > 1) print(gdens_min + ggtitle(sprintf("%s", useasons[iseason])))
    if (nrow(density_data) > 1) print(gdens_max + ggtitle(sprintf("%s", useasons[iseason])))
    par(op)
  }
}


```